import dress1 from "../assets/products/dress1.webp";
import dress2 from "../assets/products/dress2.webp";
import dress3 from "../assets/products/dress3.webp";
import dress4 from "../assets/products/dress4.webp";
import dress5 from "../assets/products/dress5.webp";
import dress6 from "../assets/products/dress6.webp";
import dress7 from "../assets/products/dress7.webp";
import dress8 from "../assets/products/dress8.webp";

export const productList = [
  {
    id: 1,
    title: "Purple Pabna Cotton Monipuri Buti Saree",
    price: 3500,
    mrpPrice: 4201,
    description:
      "Green texture printed vortex-viscose-cotton kameez with purple embroidery. Comes with green printed vortex-viscose-cotton shalwar and matching printed viscose-cotton dupatta with tassels.",
    size: ["s", "m", "l", "xl"],
    category: "woman",
    image: dress1,
    quintity: 20,
    sku: "AB-125486",
    label: "Best Seller",
    availability: "In stock",
  },
  {
    id: 2,
    title: "Pink Printed and Embroidered Cotton Saree",
    price: 2540,
    mrpPrice: 3251,
    description:
      "Black printed cotton kameez with embroidery. Comes with matching cotton shalwar and white cotton dupatta.",
    size: ["s", "m", "l", "xl"],
    category: "woman",
    image: dress2,
    quintity: 25,
    sku: "ABC-145487",
    availability: "In stock",
  },
  {
    id: 3,
    title: "Yellow Ochre Printed and Embroidered Muslin Saree",
    price: 1452,
    mrpPrice: 0,
    description:
      "Crimson red dobby texture printed viscose-cotton kameez with golden, copper, olive, orange, pink, yellow, pastel green and mint embroidery. Comes with crimson red cotton shalwar and matching printed vortex-cotton dupatta with tassels.",
    size: ["s", "m", "l", "xl"],
    category: "woman",
    image: dress3,
    quintity: 12,
    sku: "GB-125486",
    label: "Limited Stock",
    availability: "In stock",
  },
  {
    id: 4,
    title: "Mint Embroidered Balkan Fusion Theme Shalwar Kameez",
    price: 2540,
    mrpPrice: 3432,
    description:
      "Brown printed endi silk panjabi with white embroidery. Features in-seam side pockets.",
    size: ["s", "m", "l", "xl"],
    category: "man",
    image: dress4,
    quintity: 18,
    sku: "BC-125486",
    availability: "Out of stock",
  },
  {
    id: 5,
    title: "Turquoise Printed and Embroidered Viscose-Cotton Shalwar Kameez",
    price: 520,
    mrpPrice: 652,
    description: "",
    size: ["s", "m", "l", "xl"],
    category: "man",
    image: dress5,
    quintity: 14,
    sku: "CB-125486",
    label: "Best Seller",
    availability: "Out of stock",
  },
  {
    id: 6,
    title: "Kameez printed and Embroidered Viscose-Cotton Shalwar",
    price: 720,
    mrpPrice: 680,
    description: "",
    size: ["s", "m", "l", "xl"],
    category: "man",
    image: dress6,
    quintity: 14,
    sku: "FB-125486",
    label: "Best Seller",
    availability: "Out of stock",
  },
  {
    id: 7,
    title: "Kameez printed and Embroidered Viscose-Cotton Shalwar",
    price: 720,
    mrpPrice: 680,
    description: "",
    size: ["s", "m", "l", "xl"],
    category: "man",
    image: dress7,
    quintity: 14,
    sku: "FB-125486",
    label: "Best Seller",
    availability: "Out of stock",
  },
  {
    id: 8,
    title: "Kameez printed and Embroidered Viscose-Cotton Shalwar",
    price: 720,
    mrpPrice: 680,
    description: "",
    size: ["s", "m", "l", "xl"],
    category: "man",
    image: dress8,
    quintity: 14,
    sku: "FB-125486",
    label: "Best Seller",
    availability: "Out of stock",
  },
];
